// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNO7Y_yNR4_iwUvQ0TxMgzixT06fubYuc',
    appId: '1:345069564615:web:c7737d1f9a51d3667f04e2',
    messagingSenderId: '345069564615',
    projectId: 'comidapp-cd4a2',
    authDomain: 'comidapp-cd4a2.firebaseapp.com',
    storageBucket: 'comidapp-cd4a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgz09FvArN8ZTeCFMhK4I2dX-rB5covWU',
    appId: '1:345069564615:android:8899adf6725806e77f04e2',
    messagingSenderId: '345069564615',
    projectId: 'comidapp-cd4a2',
    storageBucket: 'comidapp-cd4a2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNO7Y_yNR4_iwUvQ0TxMgzixT06fubYuc',
    appId: '1:345069564615:web:50e43081c5818d407f04e2',
    messagingSenderId: '345069564615',
    projectId: 'comidapp-cd4a2',
    authDomain: 'comidapp-cd4a2.firebaseapp.com',
    storageBucket: 'comidapp-cd4a2.firebasestorage.app',
  );
}
